name: Docker Image PR

on:
  pull_request:

env:
  IMAGE_NAME: inclusivedesign/node-browsers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build .
